In [21]:
import sys

sys.path.append("../..")

from components.exog_influences import ExogenousInfluences
from components.nl_sampler import NL_function_generator

import numpy as np
import matplotlib.pyplot as plt

In [22]:
# Example usage of NL_function_generator. Which are seperate variables that are leveraged to model instantaneous exogenous effects.
# Here we generate samples from the power family.

NL = NL_function_generator()


Ex = ExogenousInfluences(
    n_vars=3,
    n_exogs=2,
    link_proba=0.0,
    param_range=[0.3, 0.5],
    mirror_range=True,
    nonlinear_proba=0.5,
    nl_sampler=NL,
)

In [ ]:
# The main functionality of the generator is "init_exogs" which initializes the exogenous influence
# structure according to the specified parameters and "get_exogs_influence" which returns influence samples.

Ex.init_exogs()
# Returns the effect as well as the exogenous samples
effect, exog_samples = Ex.get_exogs_influence()
print(effect)
print(Ex.links)
print(exog_samples)


[[0.]
 [0.]
 [0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[ 2.0350733  -0.08709417]


In [53]:
# Nonlinear effects can be modelled. A NL sampler has to be provided
NL = NL_function_generator()

Ex = ExogenousInfluences(
    n_vars=3,
    n_exogs=2,
    link_proba=0.3,
    nonlinear_proba=0.5,
    nl_sampler=NL,
)

Ex.init_exogs()
# Returns the effect as well as the exogenous samples
effect, exog_samples = Ex.get_exogs_influence()
print(Ex.links)
print(exog_samples)
print(Ex.nl_naming)

print(effect)

[[ 0.          0.          0.        ]
 [ 0.43947361  0.         -0.49512447]]
[ 0.8784503  -0.04992591]
[['Nothing' '0.5786064305276953' 'Nothing']
 ['Nothing' '1.9554584787015834' 'Nothing']]
[[-0.02194112]
 [ 0.        ]
 [ 0.02471954]]


In [62]:
# A mask can be provided to force specifc links to be present:
NL = NL_function_generator()

Ex = ExogenousInfluences(
    link_proba=0.0,
    nonlinear_proba=0.0,
    nl_sampler=NL,
)

# Bool Mask example:
mask = np.zeros((2, 3)).astype(bool)
mask[0, 1] = True

for x in range(3):
    Ex.init_exogs(link_mask=mask)
    print(Ex.links[0][1])


# Float Mask example:
mask = np.zeros((2, 3)).astype(float)
mask[0, 1] = 0.3

for x in range(3):
    Ex.init_exogs(link_mask=mask)
    print(Ex.links[0][1])


Ex = ExogenousInfluences(link_proba=0.0, nonlinear_proba=0.0, nl_sampler=NL)

# NL Mask example: (Note float masking for nl is not supported as it
# is ambiguous given the nature of the distributions over NL functions.)
# To enforce the link to exist, the link_mask has to be set to True.
nl_mask = np.zeros((2, 3)).astype(bool)
nl_mask[0, 1] = True
for x in range(3):
    Ex.init_exogs(nl_mask=nl_mask, link_mask=nl_mask)
    print(Ex.links)
    print(Ex.nl_naming)


-0.38777568795041045
0.4263328798244129
0.39514098524518676
0.3
0.3
0.3
[[ 0.         -0.38777569  0.        ]
 [ 0.          0.          0.        ]]
[['Nothing' '0.5786064305276953' 'Nothing']
 ['Nothing' 'Nothing' 'Nothing']]
[[0.         0.42633288 0.        ]
 [0.         0.         0.        ]]
[['Nothing' '0.5683048953242454' 'Nothing']
 ['Nothing' 'Nothing' 'Nothing']]
[[0.         0.39514099 0.        ]
 [0.         0.         0.        ]]
[['Nothing' '1.945891577553834' 'Nothing']
 ['Nothing' 'Nothing' 'Nothing']]
