In [1]:
from calibration_tools import eval_cross_corr_performance, check_violation_range
import numpy as np
from hydra import initialize, compose

In [2]:
%load_ext autoreload
%autoreload 2

# $V_{inno,weib,uniform}$

In [3]:
# Should not hurt the baseline. Interestingly it gets slightly better? Probably through signal strength increase (less values arround 0).
with initialize(version_base=None, config_path="../../config/"):
    cfg = compose(config_name="generate_dataset.yaml")
fail_rate = []
performance_stack = []
for x in [0, 0.2, 0.4, 0.6, 0.8, 1.0]:
    cfg.generator.inno_n.additive = True
    cfg.generator.inno_n.which_non_gaussian = "weibull"
    cfg.generator.inno_n.non_gaussian_additive = x
    res, fails = check_violation_range(cfg)
    performance_stack.append(res)
    fail_rate.append(fails)  
print(np.array(performance_stack).round(5))
print(np.array(fail_rate).sum())

[0.93912 0.92984 0.93202 0.93676 0.94782 0.96655]
0


In [4]:
with initialize(version_base=None, config_path="../../config/"):
    cfg = compose(config_name="generate_dataset.yaml")
fail_rate = []
performance_stack = []
for x in [0, 0.2, 0.4, 0.6, 0.8, 1.0]:
    cfg.generator.inno_n.additive = True
    cfg.generator.inno_n.which_non_gaussian = "uniform"
    cfg.generator.inno_n.non_gaussian_additive = x
    res, fails = check_violation_range(cfg)
    performance_stack.append(res)
    fail_rate.append(fails)  
print(np.array(performance_stack).round(5))
print(np.array(fail_rate).sum())

[0.93912 0.93225 0.92894 0.92595 0.9233  0.92592]
0


# $V_{inno}$

As the effects are differing and some noise types introduce convergent behaviour at 100%, we calibrate them individually.

In [19]:
# full 1 is not possible as the time series will degenerate (e.g., arbitrarily small).
with initialize(version_base=None, config_path="../../config/"):
    cfg = compose(config_name="generate_dataset.yaml")
performance_stack = []
fail_rate = []
for x in [0, 0.91, 0.93, 0.95, 0.97, 0.99]:
    cfg.generator.inno_n.multiplicative = True
    cfg.generator.inno_n.non_additive_noise_proba = x
    res, fails = check_violation_range(cfg, verbose=0)
    performance_stack.append(res)
    fail_rate.append(fails)  
print(np.array(performance_stack).round(5))
print(np.array(fail_rate).sum())

[0.93912 0.90077 0.89647 0.8895  0.86942 0.77654]
0


In [14]:
with initialize(version_base=None, config_path="../../config/"):
    cfg = compose(config_name="generate_dataset.yaml")
performance_stack = []
fail_rate = []
for x in [0, 0.8, 0.85, 0.9, 0.95, 1]:
    cfg.generator.inno_n.time_dependent = True
    cfg.generator.inno_n.non_additive_noise_proba = x
    res, fails = check_violation_range(cfg)
    performance_stack.append(res)
    fail_rate.append(fails)  
print(np.array(performance_stack).round(5))
print(np.array(fail_rate).sum())

[0.93912 0.93377 0.93401 0.93416 0.93412 0.93445]
0


In [24]:
# full 1 is not possible as the time series will degenerate (e.g., arbitrarily small for autocorrelation cases).
with initialize(version_base=None, config_path="../../config/"):
    cfg = compose(config_name="generate_dataset.yaml")
performance_stack = []
fail_rate = []
for x in [0, 0.35, 0.5, 0.65, 0.8, 0.95]:
    cfg.generator.inno_n.autoregressive = True
    cfg.generator.inno_n.non_additive_noise_proba = x
    res, fails = check_violation_range(cfg, verbose=0)
    performance_stack.append(res)
    fail_rate.append(fails)  
print(np.array(performance_stack).round(5))
print(np.array(fail_rate).sum())

[0.93912 0.90659 0.8541  0.77148 0.68064 0.61065]
0


In [34]:
with initialize(version_base=None, config_path="../../config/"):
    cfg = compose(config_name="generate_dataset.yaml")
performance_stack = []
fail_rate = []
for x in [0, 0.475, 0.60625, 0.7375, 0.86875, 1]:
    cfg.generator.inno_n.common = True
    cfg.generator.inno_n.non_additive_noise_proba = x
    res, fails = check_violation_range(cfg)
    performance_stack.append(res)
    fail_rate.append(fails)  
print(np.array(performance_stack).round(5))
print(np.array(fail_rate).sum())

[0.93912 0.90698 0.84322 0.79251 0.77438 0.76868]
0


In [35]:
# Doesnt seem to do much...
with initialize(version_base=None, config_path="../../config/"):
    cfg = compose(config_name="generate_dataset.yaml")
performance_stack = []
fail_rate = []
for x in [0, 0.8, 0.85, 0.9, 0.95, 1]:
    cfg.generator.inno_n.shock = True
    cfg.generator.inno_n.non_additive_noise_proba = x
    res, fails = check_violation_range(cfg)
    performance_stack.append(res)
    fail_rate.append(fails)  
print(np.array(performance_stack).round(5))
print(np.array(fail_rate).sum())

[0.93912 0.91055 0.9087  0.90817 0.90814 0.90855]
0


In [36]:
with initialize(version_base=None, config_path="../../config/"):
    cfg = compose(config_name="generate_dataset.yaml")
performance_stack = []
fail_rate = []
for x in [0, 0.8, 0.85, 0.9,0.95, 1]:
    cfg.generator.inno_n.non_additive_noise_proba = x
    cfg.generator.inno_n.semi_synthetic=True
    cfg.generator.inno_n.semi_synthetic_noise_path = "../semi_synthetic_bases/"
    res, fails = check_violation_range(cfg, verbose=0)
    performance_stack.append(res)
    fail_rate.append(fails)  
print(np.array(performance_stack).round(5))
print(np.array(fail_rate).sum())

[0.93775 0.90703 0.86723 0.83371 0.74506 0.63072]
0


# $V_{inno,var}$

In [49]:
# We cant scale it too high as the time series becomes unstable. This range seems to be interesting.
with initialize(version_base=None, config_path="../../config/"):
    cfg = compose(config_name="generate_dataset.yaml")
performance_stack = []
fail_rate = []
ranges = [
[1,1,1,1],[0.55,0.75,1.25,1.45],
[0.4125,0.6125,1.3875,1.5875],
[0.275,0.475,1.525,1.725],
[0.1375,0.3375,1.6625,1.8625],
[0.,0.2,1.8,2]
]

for x in ranges:
    cfg.generator.inno_n.non_equal_variance_range= x
    res, fails = check_violation_range(cfg)
    performance_stack.append(res)
    fail_rate.append(fails)  
print(np.array(performance_stack).round(5))
print(np.array(fail_rate).sum())

[0.94179 0.90222 0.87855 0.85345 0.83365 0.80677]
0


## $V_{obs}$

In [64]:
#Just do a single level here as we want to compare types of noise. We choose the base noise type (additive) to calibrate.
with initialize(version_base=None, config_path="../../config/"):
    cfg = compose(config_name="generate_dataset.yaml")
performance_stack = []
fail_rate = []
for x in [None, 1.1, 0.8375, 0.575, 0.3125, 0.05]:
    cfg.generator.obs_n.snr = x
    cfg.generator.obs_n.additive = True
    res, fails = check_violation_range(cfg)
    performance_stack.append(res)
    fail_rate.append(fails)
print(np.array(performance_stack).round(5))
print(np.array(fail_rate).sum())

[0.93912 0.90489 0.88801 0.8487  0.73739 0.53689]
0
